export const FETCH_SHOES_SUCCESS = 'FETCH_SHOES_SUCCESS';
export const FETCH_SHOES_FAILED = 'FETCH_SHOES_FAILED';
export const FETCH_SHOE_BY_ID_SUCCESS = 'FETCH_SHOE_BY_ID_SUCCESS';
export const FETCH_SHOE_BY_ID_FAILED = 'FETCH_SHOE_BY_ID_FAILED';
export const SET_SHOE_FILTER = 'SET_SHOE_FILTER';
export const EMPTY_SHOE_STATE = 'EMPTY_SHOE_STATE';
export const SHOW_QUICKVIEW = 'SHOW_QUICKVIEW';
export const CLOSE_QUICKVIEW = 'CLOSE_QUICKVIEW';

export const Filters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_FEATURED: 'SHOW_FEATURED',
	SHOW_ADIDAS: 'SHOW_ADIDAS',
	SHOW_JORDAN: 'SHOW_JORDAN',
	SHOW_NIKE: 'SHOW_NIKE'
}

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';