export const ShoeActions = {
	FETCH_SHOES_SUCCESS: 'FETCH_SHOES_SUCCESS',
	FETCH_SHOES_FAILED: 'FETCH_SHOES_FAILED',
	FETCH_SHOE_BY_ID_SUCCESS: 'FETCH_SHOE_BY_ID_SUCCESS',
	FETCH_SHOE_BY_ID_FAILED: 'FETCH_SHOE_BY_ID_FAILED',
	SET_SHOE_FILTER: 'SET_SHOE_FILTER',
	SHOW_QUICKVIEW: 'SHOW_QUICKVIEW',
	CLOSE_QUICKVIEW: 'CLOSE_QUICKVIEW',
	SET_SHOE_SIZE: 'SET_SHOE_SIZE'
}

export const Filters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_FEATURED: 'SHOW_FEATURED',
	SHOW_ADIDAS: 'SHOW_ADIDAS',
	SHOW_JORDAN: 'SHOW_JORDAN',
	SHOW_NIKE: 'SHOW_NIKE',
}

export const CartActions = {
	ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
	ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
}

export const CheckoutActions = {
	INPUT_CHANGE: 'INPUT_CHANGE',
	SUBMIT_CHECKOUT: 'SUBMIT_CHECKOUT'
}