export const ShoeActions = {
	FETCH_SHOES_SUCCESS: 'FETCH_SHOES_SUCCESS',
	FETCH_SHOES_FAILED: 'FETCH_SHOES_FAILED',
	FETCH_SHOE_BY_ID_SUCCESS: 'FETCH_SHOE_BY_ID_SUCCESS',
	FETCH_SHOE_BY_ID_FAILED: 'FETCH_SHOE_BY_ID_FAILED',
	SET_SHOE_FILTER: 'SET_SHOE_FILTER',
	SHOW_QUICKVIEW: 'SHOW_QUICKVIEW',
	CLOSE_QUICKVIEW: 'CLOSE_QUICKVIEW',
	SET_SHOE_SIZE: 'SET_SHOE_SIZE',
	CHANGE_ACTIVE_SHOE_IMAGE: 'CHANGE_ACTIVE_SHOE_IMAGE'
}

export const Filters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_FEATURED: 'SHOW_FEATURED',
	SHOW_ADIDAS: 'SHOW_ADIDAS',
	SHOW_JORDAN: 'SHOW_JORDAN',
	SHOW_NIKE: 'SHOW_NIKE',
}

export const CartActions = {
	ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
	ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
}

export const AccountActions = {
	ACCOUNT_INPUT_CHANGE: 'ACCOUNT_INPUT_CHANGE',
	SUBMIT_REGISTER_SUCCESS: 'SUBMIT_REGISTER_SUCCESS',
	SUBMIT_REGISTER_FAILURE: 'SUBMIT_REGISTER_FAILURE',
	SUBMIT_LOGIN_SUCCESS: 'SUBMIT_LOGIN_SUCCESS',
	SUBMIT_LOGIN_FAILURE: 'SUBMIT_LOGIN_FAILURE',
	RESET_ACCOUNT_INPUTS: 'RESET_ACCOUNT_INPUTS',
}

export const CheckoutActions = {
	CHECKOUT_INPUT_CHANGE: 'CHECKOUT_INPUT_CHANGE',
	SUBMIT_CHECKOUT: 'SUBMIT_CHECKOUT'
}

export const ReviewActions = {
	GET_REVIEWS_BY_SHOEID_SUCCESS: 'GET_REVIEWS_SUCCESS',
	GET_REVIEWS_BY_SHOEID_FAILURE: 'GET_REVIEWS_FAILURE',
	CHANGE_REVIEW_RATING: 'CHANGE_REVIEW_RATING',
	CHANGE_REVIEW_TEXT: 'CHANGE_REVIEW_TEXT',
	POST_NEW_REVIEW_SUCCESS: 'POST_NEW_REVIEW_SUCCESS',
	POST_NEW_REVIEW_FAILURE: 'POST_NEW_REVIEW_FAILURE',
	RESET_REVIEWS: 'RESET_REVIEWS'
}